# Generated by Django 2.2.2 on 2019-06-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
    ]
